blank_issues_enabled: false
contact_links:
  - name: General Questions about OpenMined
    url: https://slack.openmined.org
    about: Our Slack community is a great place to ask general questions about OpenMined and it's projects
